FROM nginx:alpine as build

RUN apk update && apk add --no-cache bash git openssh

RUN git clone -b master https://github.com/RicardoGaefke/ricardogaefke-webjobs.git ./app

FROM nginx:alpine as publish

WORKDIR /app

COPY --from=build /nginx/default.cloud.conf /etc/nginx/conf.d/default.conf