FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

RUN apk update && apk add --no-cache bash git openssh nodejs npm

WORKDIR /app

COPY *.sln .
COPY src/. ./src/

WORKDIR /app/src/Web.Site

RUN npm install

RUN npm run build

RUN dotnet publish -c Release ./Web.Site.csproj -r linux-musl-x64 -o ./publish

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine as runtime

RUN apk update && apk add --no-cache nodejs npm nodejs-npm

ENV ASPNETCORE_URLS=http://+:5000

WORKDIR /app

COPY --from=build /app/src/Web.Site/publish ./

ENTRYPOINT ["./Web.Site"]

# docker build -f .\Dockerfile.web.admin.dev -t web_admin_dev --no-cache .
# docker create web_admin_dev
# docker run -it -t -p 8000:5000 web_admin_dev
# /usr/bin/node /usr/share/doc/nodejs
